[build]
  command = "echo 'no op'"
  publish = "public"

  functions = "functions/"

  [build.environment]
    YARN_FLAGS = "--frozen-lockfile"
    YARN_VERSION = "1.22.4"
    NODE_VERSION = "12"
    
